#!/usr/bin/env Rscript
# Generate TikZ \foreach data lists for fig-categorymap.tex from the frozen
# per-category CSVs (categorymap_{mvtec,visa,mpdd}.csv), which are themselves
# pooled (mean over 5 seeds x 2 backbones) straight out of the frozen
# gate_calibration/v1_*_seed*.json records. This step performs no numeric
# computation; it only reformats already-pooled CSV rows into a TikZ list
# literal. This keeps the production figure pipeline R-only.

HERE <- tryCatch(dirname(sub("^--file=", "",
          grep("^--file=", commandArgs(FALSE), value = TRUE)[1])),
          error = function(e) getwd())
if (is.na(HERE) || HERE == "") HERE <- getwd()

BENCHES <- c("mvtec", "visa", "mpdd")

DISPLAY_LABELS <- list(
  mvtec = c(
    bottle = "bottle", cable = "cable", capsule = "caps.", carpet = "carpet",
    grid = "grid", hazelnut = "hazel.", leather = "leather", "metal nut" = "m-nut",
    pill = "pill", screw = "screw", tile = "tile", toothbrush = "t-brush",
    transistor = "trans.", wood = "wood", zipper = "zipper"
  ),
  visa = c(
    candle = "candle", capsules = "caps.", cashew = "cashew", chewinggum = "chew.",
    fryum = "fryum", macaroni1 = "mac-1", macaroni2 = "mac-2", pcb1 = "pcb-1",
    pcb2 = "pcb-2", pcb3 = "pcb-3", pcb4 = "pcb-4", "pipe fryum" = "pipe"
  ),
  mpdd = c(
    "bracket black" = "b-blk", "bracket brown" = "b-brn",
    "bracket white" = "b-wht", connector = "conn",
    "metal plate" = "plate", tubes = "tubes"
  )
)

for (bench in BENCHES) {
  csv_path <- file.path(HERE, sprintf("categorymap_%s.csv", bench))
  # drop comment lines starting with '#'
  raw <- readLines(csv_path, warn = FALSE)
  raw <- raw[!grepl("^#", raw)]
  df <- read.csv(text = paste(raw, collapse = "\n"), stringsAsFactors = FALSE,
                 check.names = FALSE, colClasses = "character")
  labmap <- DISPLAY_LABELS[[bench]]
  rows <- character(nrow(df))
  for (i in seq_len(nrow(df))) {
    disp <- labmap[[ df$label[i] ]]
    if (is.null(disp)) stop(sprintf("no display label for %s::%s", bench, df$label[i]))
    rows[i] <- sprintf("%s/%s/%s/%s/%s", disp,
                       df$g1_cert[i], df$g1_rate_pct[i],
                       df$g2_cert[i], df$g2_rate_pct[i])
  }
  out_path <- file.path(HERE, sprintf("categorymap_%s.tex", bench))
  lines <- c(
    sprintf("%% AUTO-GENERATED by gen_categorymap_tex.R from categorymap_%s.csv -- do not hand-edit.", bench),
    sprintf("\\newcommand{\\%slist}{%s}", bench, paste(rows, collapse = ", ")),
    sprintf("\\newcommand{\\%sncat}{%d}", bench, length(rows))
  )
  writeLines(lines, out_path, useBytes = TRUE)
  cat("wrote", out_path, "(", length(rows), "categories )\n")
}
