#!/usr/bin/env python3
"""Generate TikZ \\foreach data lists for fig-categorymap.tex from the frozen
per-category CSVs (categorymap_{mvtec,visa,mpdd}.csv), which are themselves
pooled (mean over 5 seeds x 2 backbones) straight out of the frozen
gate_calibration/v1_*_seed*.json records -- see manuscripts/figures-src/README
for the extraction script. This step performs no numeric computation; it only
reformats already-pooled CSV rows into a TikZ-readable list literal.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))

BENCHES = ["mvtec", "visa", "mpdd"]

for bench in BENCHES:
    rows = []
    with open(os.path.join(HERE, f"categorymap_{bench}.csv")) as f:
        r = csv.DictReader(row for row in f if not row.startswith("#"))
        for row in r:
            rows.append(
                f"{row['label']}/{row['g1_cert']}/{row['g1_rate_pct']}/"
                f"{row['g2_cert']}/{row['g2_rate_pct']}"
            )
    out_path = os.path.join(HERE, f"categorymap_{bench}.tex")
    with open(out_path, "w") as f:
        f.write(f"% AUTO-GENERATED by gen_categorymap_tex.py from categorymap_{bench}.csv -- do not hand-edit.\n")
        f.write(f"\\newcommand{{\\{bench}list}}{{{', '.join(rows)}}}\n")
        f.write(f"\\newcommand{{\\{bench}ncat}}{{{len(rows)}}}\n")
    print("wrote", out_path, "(", len(rows), "categories )")
