#!/usr/bin/env Rscript
# Normalize the frozen Inspect AEI Mondrian result into deterministic TikZ rows.
# The JSON input is never modified. Generated files are local build inputs.

args <- commandArgs(trailingOnly = TRUE)
script_arg <- grep("^--file=", commandArgs(), value = TRUE)
script_path <- if (length(script_arg)) sub("^--file=", "", script_arg[[1]]) else "normalize_mondrian.R"
script_dir <- normalizePath(dirname(script_path), mustWork = TRUE)
input <- if (length(args) >= 1) args[[1]] else file.path(script_dir, "../../../mondrian_2026-07-19/results.json")
out_dir <- if (length(args) >= 2) args[[2]] else file.path(script_dir, "../out")
# Keep generated artifacts under figures-src (parent of R/).
allowed_root <- normalizePath(file.path(script_dir, ".."), winslash = "/", mustWork = TRUE)
out_abs <- normalizePath(out_dir, winslash = "/", mustWork = FALSE)
if (!(identical(out_abs, allowed_root) || startsWith(out_abs, paste0(allowed_root, "/")))) {
  stop("out_dir must be under ", allowed_root, "; got ", out_abs)
}

if (!requireNamespace("jsonlite", quietly = TRUE)) stop("R package jsonlite is required")
if (!requireNamespace("digest", quietly = TRUE)) stop("R package digest is required")
if (!file.exists(input)) stop("frozen input not found: ", input)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
d <- jsonlite::fromJSON(input, simplifyVector = FALSE)
backbones <- c("patchcore", "dinomaly")
categories <- c("bottle", "cable", "capsule", "carpet", "grid", "hazelnut", "leather",
                "metal_nut", "pill", "screw", "tile", "toothbrush", "transistor", "wood", "zipper")
parts <- list(c("bottle", "cable", "capsule", "carpet", "grid", "hazelnut", "leather"),
              c("metal_nut", "pill", "screw", "tile", "toothbrush", "transistor", "wood", "zipper"))

tex_escape <- function(x) {
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x <- gsub("~", "\\\\textasciitilde{}", x, fixed = TRUE)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}
rate_value <- function(cell, key) {
  value <- cell[[key]]
  if (is.null(value) || length(value) == 0 || is.na(value)) return(NA_real_)
  as.numeric(value)
}
int_value <- function(cell, key) as.integer(cell[[key]])
fmt_rate <- function(value) if (is.na(value)) "" else sprintf("%.1f", 100 * value)
fmt_int <- function(value) sprintf("%d", as.integer(value))

rows <- list()
for (cat in categories) {
  types <- sort(unique(c(names(d[["patchcore"]][[cat]]), names(d[["dinomaly"]][[cat]]))))
  for (typ in types) {
    pc <- d[["patchcore"]][[cat]][[typ]]
    di <- d[["dinomaly"]][[cat]][[typ]]
    if (is.null(pc) || is.null(di)) stop("backbone row mismatch: ", cat, "::", typ)
    rows[[length(rows) + 1L]] <- data.frame(
      category = cat, defect_type = typ,
      pc_miss = rate_value(pc, "miss_rate"), pc_defer = rate_value(pc, "deferral_rate"),
      di_miss = rate_value(di, "miss_rate"), di_defer = rate_value(di, "deferral_rate"),
      pc_n_def = int_value(pc, "n_def"), pc_n = int_value(pc, "n"),
      di_n_def = int_value(di, "n_def"), di_n = int_value(di, "n"),
      stringsAsFactors = FALSE
    )
  }
}
rows <- do.call(rbind, rows)
if (nrow(rows) != 88L) stop("expected 88 normalized rows, found ", nrow(rows))
if (anyDuplicated(rows[c("category", "defect_type")])) stop("duplicate normalized row")
if (!identical(sort(unique(rows$category)), sort(categories))) stop("category roster changed")

canonical <- paste(apply(rows, 1, function(r) paste(ifelse(is.na(r), "NA", r), collapse = "|")), collapse = "\n")
digest <- digest::digest(canonical, algo = "sha256", serialize = FALSE)
writeLines(c(paste0("input=", normalizePath(input, mustWork = TRUE)),
             paste0("rows=", nrow(rows)),
             paste0("sha256=", digest)), file.path(out_dir, "mondrian_cells.sha256"))
writeLines(c("category|defect_type|pc_miss|pc_defer|di_miss|di_defer|pc_n_def|pc_n|di_n_def|di_n", canonical),
           file.path(out_dir, "mondrian_cells.tsv"))

write_part <- function(part_rows, part_id) {
  n <- nrow(part_rows)
  # Keep these in lockstep with tikz/mondrian_common.tex (\topline/\rowpitch/\legendband).
  # height = header band + n row pitches + bottom legend band; last row sits on y=legend_band.
  topline <- 0.58
  rowpitch <- 0.178
  legend_band <- 0.76
  height <- topline + rowpitch * n + legend_band
  path <- file.path(out_dir, sprintf("mondrian-%d-rows.tex", part_id))
  con <- file(path, open = "wt")
  on.exit(close(con), add = TRUE)
  writeLines(sprintf("%% generated by normalize_mondrian.R; rows=%d; sha256=%s", n, digest), con)
  writeLines(sprintf("\\renewcommand{\\nrows}{%d}", n), con)
  writeLines(sprintf("\\renewcommand{\\figureheight}{%.3f}", height), con)
  for (i in seq_len(n)) {
    r <- part_rows[i, ]
    first_in_category <- i == 1L || part_rows$category[i] != part_rows$category[i - 1L]
    # Emit a category-boundary rule at the top of the first row of each category.
    separator <- if (first_in_category) 1L else 0L
    fields <- c(separator, tex_escape(r$category), tex_escape(r$defect_type),
                fmt_rate(r$pc_miss), fmt_rate(r$pc_defer), fmt_rate(r$di_miss), fmt_rate(r$di_defer),
                fmt_int(r$pc_n_def), fmt_int(r$pc_n), fmt_int(r$di_n_def), fmt_int(r$di_n))
    writeLines(do.call(sprintf, c(list("\\mondrianrow{%s}{%s}{%s}{%s}{%s}{%s}{%s}{%s}{%s}{%s}{%s}"), as.list(fields))), con)
  }
}
for (part_id in seq_along(parts)) write_part(rows[rows$category %in% parts[[part_id]], ], part_id)

writeLines(c(sprintf("input: %s", normalizePath(input, mustWork = TRUE)),
             sprintf("rows: %d (part 1: %d, part 2: %d)", nrow(rows),
                     sum(rows$category %in% parts[[1]]), sum(rows$category %in% parts[[2]])),
             sprintf("sha256: %s", digest)), stdout())
