#!/usr/bin/env Rscript
# Process alpha_sweep data for fig-alphafrontier
# Reads: alpha_sweep_2026-07-19/results.json
# Writes: R/alphafrontier_data.csv

library(jsonlite)

# Suppress warnings during fromJSON - we handle structure carefully
options(warn = 1)  # Print warnings as they occur

script_arg <- grep("^--file=", commandArgs(), value = TRUE)
script_path <- if (length(script_arg)) sub("^--file=", "", script_arg[[1]]) else "process_alphafrontier.R"
script_dir <- normalizePath(dirname(script_path), mustWork = TRUE)
json_path <- normalizePath(file.path(script_dir, "../../../alpha_sweep_2026-07-19/results.json"), mustWork = TRUE)
setwd(script_dir)

d <- fromJSON(json_path, simplifyVector = FALSE, simplifyDataFrame = FALSE)

BENCHES <- list(
  list(key="mvtec", label="MVTec-AD", ncats=15),
  list(key="visa", label="VisA", ncats=12),
  list(key="mpdd", label="MPDD", ncats=6)
)
GRID_MISS <- c(0.20, 0.10, 0.05, 0.02, 0.01)
AF_FIXED <- 0.05
BACKBONES <- c("patchcore", "dinomaly")

rows <- list()
for (bench_info in BENCHES) {
  bk <- bench_info$key
  blabel <- bench_info$label
  ncats <- bench_info$ncats

  for (bb in BACKBONES) {
    for (am in GRID_MISS) {
      # JSON keys use %g (am0.2_af0.05), not %.2f (am0.20_af0.05).
      cell_key <- sprintf("am%g_af%g", am, AF_FIXED)
      cell <- d[[bk]][[bb]][[cell_key]]
      if (is.null(cell)) {
        stop(sprintf("FATAL: missing alpha-sweep cell %s/%s/%s", bk, bb, cell_key))
      }

      seed_defs <- numeric()
      seed_certs <- numeric()

      per_seed <- cell$per_seed
      if (!is.null(per_seed) && length(per_seed) > 0) {
        for (seed_name in names(per_seed)) {
          ps <- per_seed[[seed_name]]
          if (!is.null(ps$overall_mean_deferral)) {
            seed_defs <- c(seed_defs, as.numeric(ps$overall_mean_deferral))
          }
          if (!is.null(ps$certification_counts_per_repeat$both)) {
            cc <- ps$certification_counts_per_repeat$both
            if (is.list(cc)) {
              cc_vec <- unlist(cc)
            } else {
              cc_vec <- as.numeric(cc)
            }
            seed_certs <- c(seed_certs, mean(cc_vec) / ncats)
          }
        }
      }

      if (length(seed_defs) > 0 && length(seed_certs) > 0) {
        rows[[length(rows)+1]] <- data.frame(
          benchmark = blabel,
          backbone = bb,
          alpha_miss = am,
          deferral_mean = mean(seed_defs),
          deferral_min = min(seed_defs),
          deferral_max = max(seed_defs),
          certified_mean = mean(seed_certs),
          stringsAsFactors = FALSE
        )
      }
    }
  }
}

df <- do.call(rbind, rows)
write.csv(df, "alphafrontier_data.csv", row.names = FALSE)
cat(sprintf("Wrote %d rows to alphafrontier_data.csv\n", nrow(df)))

# Emit TikZ fragments for each benchmark × metric combination
TEX_DIR <- normalizePath(file.path(getwd(), "../out"), mustWork = FALSE)
dir.create(TEX_DIR, recursive = TRUE, showWarnings = FALSE)
fmt <- function(x) format(x, digits = 4, scientific = FALSE, trim = TRUE)

BENCH_KEYS <- list(
  "MVTec-AD" = "mvtecad",
  "VisA" = "visa",
  "MPDD" = "mpdd"
)

for (bench_info in BENCHES) {
  blabel <- bench_info$label
  bench_key <- BENCH_KEYS[[blabel]]

  # Deferral fragment
  def_lines <- character(0)
  def_lines <- c(def_lines, "% generated by process_alphafrontier.R")

  for (bb in BACKBONES) {
    bb_data <- df[df$benchmark == blabel & df$backbone == bb, ]
    bb_data <- bb_data[order(bb_data$alpha_miss, decreasing = TRUE), ]

    if (nrow(bb_data) == 0) next

    coords <- paste(sprintf("(%s,%s)", fmt(bb_data$alpha_miss), fmt(bb_data$deferral_mean)), collapse = " ")

    if (bb == "patchcore") {
      def_lines <- c(def_lines, sprintf("\\addplot[cPatchcore, mark=o, line width=1.4pt, mark size=3.5pt] coordinates {"))
    } else {
      def_lines <- c(def_lines, sprintf("\\addplot[cDinomaly, mark=square, dashed, line width=1.4pt, mark size=3.5pt] coordinates {"))
    }
    def_lines <- c(def_lines, paste0("  ", coords))
    def_lines <- c(def_lines, "};")
  }

  writeLines(def_lines, file.path(TEX_DIR, sprintf("alphafrontier-%s-deferral.tex", bench_key)), useBytes = TRUE)

  # Certification fragment
  cert_lines <- character(0)
  cert_lines <- c(cert_lines, "% generated by process_alphafrontier.R")

  for (bb in BACKBONES) {
    bb_data <- df[df$benchmark == blabel & df$backbone == bb, ]
    bb_data <- bb_data[order(bb_data$alpha_miss, decreasing = TRUE), ]

    if (nrow(bb_data) == 0) next

    coords <- paste(sprintf("(%s,%s)", fmt(bb_data$alpha_miss), fmt(bb_data$certified_mean)), collapse = " ")

    if (bb == "patchcore") {
      cert_lines <- c(cert_lines, sprintf("\\addplot[cPatchcore, mark=o, line width=1.4pt, mark size=3.5pt] coordinates {"))
    } else {
      cert_lines <- c(cert_lines, sprintf("\\addplot[cDinomaly, mark=square, dashed, line width=1.4pt, mark size=3.5pt] coordinates {"))
    }
    cert_lines <- c(cert_lines, paste0("  ", coords))
    cert_lines <- c(cert_lines, "};")
  }

  writeLines(cert_lines, file.path(TEX_DIR, sprintf("alphafrontier-%s-cert.tex", bench_key)), useBytes = TRUE)
}

cat("Wrote alphafrontier TikZ fragments to ../out/\n")
