#!/usr/bin/env Rscript
# Process G2 promotion data for fig-g2delta (4 panels)
# Reads: g2_promotion_2026-07-12/G2-PROMOTION-RESULT.json
#        mpdd_results_2026-07-13/gate_calibration/v1_holdout_patchcore_seed0.json
#        remedy_pricing_2026-07-19/results.json
# Writes: R/g2delta_*.csv + out/g2delta-*.tex

library(jsonlite)

script_arg <- grep("^--file=", commandArgs(), value = TRUE)
script_path <- if (length(script_arg)) sub("^--file=", "", script_arg[[1]]) else "process_g2delta.R"
script_dir <- normalizePath(dirname(script_path), mustWork = TRUE)
setwd(script_dir)

resolve <- function(...) {
  normalizePath(file.path(script_dir, "../../..", ...), mustWork = TRUE)
}

g2 <- fromJSON(resolve("g2_promotion_2026-07-12", "G2-PROMOTION-RESULT.json"))
hold <- fromJSON(resolve(
  "mpdd_results_2026-07-13", "gate_calibration", "v1_holdout_patchcore_seed0.json"
))
rp <- fromJSON(resolve("remedy_pricing_2026-07-19", "results.json"))

mvtec_cats <- c(
  "bottle", "cable", "capsule", "carpet", "grid", "hazelnut", "leather",
  "metal_nut", "pill", "screw", "tile", "toothbrush", "transistor", "wood", "zipper"
)
mpdd_cats <- c(
  "bracket_black", "bracket_brown", "bracket_white",
  "connector", "metal_plate", "tubes"
)
MVTEC_SHORT <- c(
  bottle = "bot", cable = "cab", capsule = "cap", carpet = "car", grid = "grd",
  hazelnut = "haz", leather = "lea", metal_nut = "nut", pill = "pil", screw = "scr",
  tile = "til", toothbrush = "tbr", transistor = "tra", wood = "woo", zipper = "zip"
)
MPDD_SHORT <- c(
  bracket_black = "b-blk", bracket_brown = "b-brn", bracket_white = "b-wht",
  connector = "conn", metal_plate = "plate", tubes = "tubes"
)

# ── CSV tiles ──
mv <- g2$compare[["0"]]
mvtec_rows <- lapply(mvtec_cats, function(cat) {
  e <- mv[[cat]]
  primary_status <- if (isTRUE(e$primary_g2)) "certified" else "refused-floor"
  promoted_status <- if (isTRUE(e$promoted_g2)) {
    "certified"
  } else if (identical(e$g2_mode, "audited-not-certified")) {
    "refused-KS"
  } else {
    "refused-floor"
  }
  data.frame(
    category = cat, short = MVTEC_SHORT[[cat]],
    primary_status = primary_status, promoted_status = promoted_status,
    stringsAsFactors = FALSE
  )
})
mvtec_df <- do.call(rbind, mvtec_rows)
write.csv(mvtec_df, "g2delta_mvtec.csv", row.names = FALSE, quote = FALSE)

strata <- hold$floors
mpdd_rows <- lapply(mpdd_cats, function(cat) {
  s <- strata[[cat]]
  promoted_status <- if (isTRUE(s$g2_certified)) {
    "certified"
  } else if (identical(s$g2_mode, "audited-not-certified")) {
    "refused-KS"
  } else {
    "refused-floor"
  }
  data.frame(
    category = cat, short = MPDD_SHORT[[cat]],
    primary_status = "refused-floor", promoted_status = promoted_status,
    stringsAsFactors = FALSE
  )
})
mpdd_df <- do.call(rbind, mpdd_rows)
write.csv(mpdd_df, "g2delta_mpdd.csv", row.names = FALSE, quote = FALSE)

# ── CSV panel c: rescued-category deferral ──
rescued <- list()
for (cat in mvtec_cats) {
  if (rp$mvtec$rollup[[cat]]$n_seeds_rescued > 0) {
    rescued[[length(rescued) + 1]] <- data.frame(
      category = cat, short = MVTEC_SHORT[[cat]], bench = "MVTec AD",
      primary_deferral = rp$mvtec$rollup[[cat]]$primary_deferral_mean * 100,
      remedy_deferral = rp$mvtec$rollup[[cat]]$remedy_deferral_mean * 100,
      stringsAsFactors = FALSE
    )
  }
}
for (cat in mpdd_cats) {
  if (rp$mpdd$rollup[[cat]]$n_seeds_rescued > 0) {
    rescued[[length(rescued) + 1]] <- data.frame(
      category = cat, short = MPDD_SHORT[[cat]], bench = "MPDD",
      primary_deferral = rp$mpdd$rollup[[cat]]$primary_deferral_mean * 100,
      remedy_deferral = rp$mpdd$rollup[[cat]]$remedy_deferral_mean * 100,
      stringsAsFactors = FALSE
    )
  }
}
rescued_df <- do.call(rbind, rescued)
write.csv(rescued_df, "g2delta_deferral.csv", row.names = FALSE)

# ── CSV panel d: per-seed n_G2 ──
seeds <- 0:4
seed_df <- data.frame(
  seed = seeds,
  mvtec = vapply(seeds, function(s) g2$summary[[as.character(s)]]$n_g2_certified, numeric(1)),
  mpdd = vapply(seeds, function(s) rp$mpdd$n_g2_certified_per_seed[[as.character(s)]], numeric(1))
)
write.csv(seed_df, "g2delta_seeds.csv", row.names = FALSE)

cat("Wrote g2delta CSV files\n")

# ── TikZ fragments ──
TEX_DIR <- normalizePath(file.path(getwd(), "../out"), mustWork = FALSE)
dir.create(TEX_DIR, recursive = TRUE, showWarnings = FALSE)
fmt2 <- function(x) format(round(x, 2), nsmall = 2, scientific = FALSE, trim = TRUE)

color_for <- function(status) {
  if (status == "certified") return("cCertified")
  if (status == "refused-KS") return("cRefuseKS")
  "cRefuseFloor"
}

emit_tiles <- function(df, outfile) {
  lines <- c("% generated by process_g2delta.R")
  for (i in seq_len(nrow(df))) {
    idx <- i - 1L
    lines <- c(lines,
      sprintf("\\fill[%s] (%d,0) rectangle ++(1,1);", color_for(df$promoted_status[i]), idx),
      sprintf("\\fill[%s] (%d,1) rectangle ++(1,1);", color_for(df$primary_status[i]), idx),
      sprintf("\\draw[white, line width=1.5pt] (%d,0) rectangle ++(1,2);", idx))
  }
  writeLines(lines, outfile, useBytes = TRUE)
}
emit_tiles(mvtec_df, file.path(TEX_DIR, "g2delta-mvtec-tiles.tex"))
emit_tiles(mpdd_df, file.path(TEX_DIR, "g2delta-mpdd-tiles.tex"))

# Panel c: dumbbell (y = n-1 .. 0 top-to-bottom as in Python)
n <- nrow(rescued_df)
panel_c <- c("% generated by process_g2delta.R -- panel c")
for (i in seq_len(n)) {
  y <- n - i
  pri <- rescued_df$primary_deferral[i]
  rem <- rescued_df$remedy_deferral[i]
  panel_c <- c(panel_c,
    sprintf("\\draw[black!20, line width=0.8pt] (axis cs:%s,%d) -- (axis cs:%s,%d);",
            fmt2(min(pri, rem)), y, fmt2(max(pri, rem)), y),
    sprintf("\\addplot[cRefuseFloor, only marks, mark=*, mark size=1.6pt, forget plot] coordinates {(%s,%d)};",
            fmt2(pri), y),
    sprintf("\\addplot[cCertified, only marks, mark=square*, mark size=1.6pt, forget plot] coordinates {(%s,%d)};",
            fmt2(rem), y))
}
# Vacuity callout to the right of the 80% line — clears top dumbbell + title chrome.
panel_c <- c(panel_c,
  sprintf("\\draw[black, dashed, line width=0.8pt] (axis cs:80,-0.5) -- (axis cs:80,%s);", n - 0.5),
  sprintf(paste0(
    "\\node[anchor=west, font=\\fontsize{7}{8}\\selectfont, align=left] ",
    "at (axis cs:82,%s) {K2 vacuity\\\\80\\%%};"
  ), fmt2((n - 1) / 2)))
writeLines(panel_c, file.path(TEX_DIR, "g2delta-panel-c.tex"), useBytes = TRUE)

# Panel d: grouped bars. Flat square legend images (not tall ybar samples) so the
# TikZ chrome can park a horizontal legend just above the title without overlap.
mv_coords <- paste(sprintf("(%s,%s)", fmt2(seed_df$seed - 0.18), fmt2(seed_df$mvtec)), collapse = " ")
mp_coords <- paste(sprintf("(%s,%s)", fmt2(seed_df$seed + 0.18), fmt2(seed_df$mpdd)), collapse = " ")
writeLines(c(
  "% generated by process_g2delta.R -- panel d",
  "\\addlegendimage{cGate, only marks, mark=square*, mark size=1.8pt}",
  "\\addlegendentry{MVTec AD}",
  "\\addlegendimage{cAccept, only marks, mark=square*, mark size=1.8pt}",
  "\\addlegendentry{MPDD}",
  sprintf("\\addplot[cGate, fill=cGate, forget plot] coordinates {%s};", mv_coords),
  sprintf("\\addplot[cAccept, fill=cAccept, forget plot] coordinates {%s};", mp_coords)
), file.path(TEX_DIR, "g2delta-panel-d.tex"), useBytes = TRUE)

# ytics for panel c
ytick <- paste(seq(0, n - 1), collapse = ",")
yticklabels <- paste(rev(rescued_df$short), collapse = ",")
# Macro names must not start with \g<digit> (TeX accent primitive).
writeLines(c(
  sprintf("\\gdef\\GtwoDeltaCYtick{%s}", ytick),
  sprintf("\\gdef\\GtwoDeltaCYticklabels{%s}", yticklabels),
  sprintf("\\gdef\\GtwoDeltaCN{%d}", n)
), file.path(TEX_DIR, "g2delta-panel-c-meta.tex"), useBytes = TRUE)

cat(sprintf("wrote g2delta fragments (%d rescued cats, %d seeds)\n", n, nrow(seed_df)))
