#!/usr/bin/env Rscript
# Process calplanning data for fig-calplanning
# Reads: calplanning_2026-07-29/results.json
# Writes: R/calplanning_*.csv  +  out/calplanning-panel-[a-d].tex

library(jsonlite)

script_arg <- grep("^--file=", commandArgs(), value = TRUE)
script_path <- if (length(script_arg)) sub("^--file=", "", script_arg[[1]]) else "process_calplanning.R"
script_dir <- normalizePath(dirname(script_path), mustWork = TRUE)
json_path <- normalizePath(file.path(script_dir, "../../../calplanning_2026-07-29/results.json"), mustWork = TRUE)
setwd(script_dir)

d <- fromJSON(json_path)   # simplifyVector=TRUE -> nested data.frames
ALPHA_MISS <- d$provenance$alpha_miss_operating_point
ALPHA_FR   <- d$provenance$alpha_fr_operating_point
BENCHES    <- c("MVTec AD", "VisA", "MPDD")

# ── CSV: requirement_curve ──
req_df <- data.frame(alpha=d$requirement_curve$alpha, min_n_cal=d$requirement_curve$min_n_cal)
write.csv(req_df, "calplanning_requirement.csv", row.names=FALSE)

# ── CSV: observed_pools ──
obs_rows <- lapply(names(d$observed_pools), function(label) {
  o <- d$observed_pools[[label]]
  data.frame(benchmark=label,
             n_cal_defect_lo=o$n_cal_defect_range[1], n_cal_defect_hi=o$n_cal_defect_range[2],
             n_cal_defect_median=o$n_cal_defect_median,
             n_cal_good_lo=o$n_cal_good_range[1], n_cal_good_hi=o$n_cal_good_range[2],
             n_cal_good_median=o$n_cal_good_median, stringsAsFactors=FALSE)
})
obs_df <- do.call(rbind, obs_rows)
write.csv(obs_df, "calplanning_observed.csv", row.names=FALSE)

# ── CSV: attainment_sweep ──
# d$attainment_sweep$g1 is a data.frame; $by_benchmark is a data.frame
# whose columns are benchmark names; each cell is an inner data.frame (patchcore/dinomaly)
att_rows <- list()
for (ax in c("g1_escaped_defect", "g2_false_reject")) {
  g     <- d$attainment_sweep[[ax]]
  bb_df <- g$by_benchmark
  for (i in seq_len(nrow(g))) {
    fracs <- numeric(0)
    for (bench in BENCHES) {
      bench_inner <- bb_df[[bench]]          # data.frame: patchcore, dinomaly cols
      for (backbone in names(bench_inner)) {
        fracs <- c(fracs, bench_inner[[backbone]]$fraction[i])
      }
    }
    att_rows[[length(att_rows)+1]] <- data.frame(
      axis=ax, alpha=g$alpha[i],
      certifiable_fraction=mean(fracs), stringsAsFactors=FALSE)
  }
}
att_df <- do.call(rbind, att_rows)
write.csv(att_df, "calplanning_attainment.csv", row.names=FALSE)

# ── CSV: pool_growth ──
pool_rows <- list()
for (ax in c("g1_escaped_defect", "g2_false_reject")) {
  pg    <- d$pool_growth[[ax]]
  bb_df <- pg$by_benchmark
  for (i in seq_len(nrow(pg))) {
    for (bench in BENCHES) {
      bench_inner <- bb_df[[bench]]
      fracs <- numeric(0)
      for (backbone in names(bench_inner)) {
        fracs <- c(fracs, bench_inner[[backbone]]$fraction[i])
      }
      pool_rows[[length(pool_rows)+1]] <- data.frame(
        axis=ax, multiplier=pg$multiplier[i], benchmark=bench,
        certifiable_fraction=mean(fracs), stringsAsFactors=FALSE)
    }
  }
}
pool_df <- do.call(rbind, pool_rows)
write.csv(pool_df, "calplanning_poolcurve.csv", row.names=FALSE)

# ── CSV: planning_rule ──
plan_rows <- list()
for (ax in c("g1_escaped_defect", "g2_false_reject")) {
  for (bench in BENCHES) {
    p    <- d$planning_rule[[ax]][[bench]]
    mult <- if (!is.null(p$smallest_multiplier_certifying_all)) p$smallest_multiplier_certifying_all else NA
    plan_rows[[length(plan_rows)+1]] <- data.frame(
      axis=ax, benchmark=bench,
      min_pool_required=p$min_pool_required, smallest_multiplier=mult,
      stringsAsFactors=FALSE)
  }
}
plan_df <- do.call(rbind, plan_rows)
write.csv(plan_df, "calplanning_planning.csv", row.names=FALSE)

writeLines(c(sprintf("ALPHA_MISS=%s", ALPHA_MISS), sprintf("ALPHA_FR=%s", ALPHA_FR)),
           "calplanning_params.txt")
cat("Wrote calplanning CSV files\n")

# ── TikZ fragment emitter ─────────────────────────────────────────────────────
TEX_DIR <- normalizePath(file.path(getwd(), "../out"), mustWork=FALSE)
dir.create(TEX_DIR, recursive=TRUE, showWarnings=FALSE)
fmt4 <- function(x) format(round(x,4), nsmall=4, scientific=FALSE, trim=TRUE)

BENCH_COLORS <- c("MVTec AD"="cMVTecAD", "VisA"="cVisA", "MPDD"="cMPDD")

# Panel a: req curve + pool bands + alpha_miss line + bench labels.
# Full α range stays inside the axis (xmin below 0.001, clip on — no left
# spillover). xmax is padded past the last data α so band labels fit INSIDE
# the frame on the right, clear of the curve and α_miss. Degenerate pools
# (lo==hi, e.g. VisA 50–50) get a thin log-space band.
pa <- c("% generated by process_calplanning.R -- panel a")
req_s <- req_df[order(req_df$alpha, decreasing=TRUE), ]
req_coords <- paste(sprintf("(%s,%d)", fmt4(req_s$alpha), as.integer(round(req_s$min_n_cal))), collapse=" ")
pa <- c(pa,
  "\\addplot[cGate, mark=o, line width=1.3pt, mark size=3.2pt] coordinates {",
  paste0("  ", req_coords), "};",
  "\\addlegendentry{$n_{\\mathrm{cal}} \\geq 1/\\alpha - 1$}")
for (bench in BENCHES) {
  o  <- obs_df[obs_df$benchmark==bench, ]
  lo <- as.numeric(o$n_cal_defect_lo)
  hi <- as.numeric(o$n_cal_defect_hi)
  if (isTRUE(all.equal(lo, hi))) {
    # ~±0.08 dex visual thickness on a log-y axis
    lo <- lo / (10^0.08)
    hi <- hi * (10^0.08)
  }
  y_lab <- exp((log(lo) + log(hi)) / 2)
  pa <- c(pa,
    sprintf("\\fill[%s, opacity=0.18] (axis cs:0.00055,%s) rectangle (axis cs:0.20,%s);",
            BENCH_COLORS[bench], fmt4(lo), fmt4(hi)),
    # Inside the band on the left (log-x headroom); avoids right-edge clip
    # when legends sit inside and xmax is not padded for external labels.
    sprintf(paste0("\\node[anchor=west, font=\\fontsize{8}{9}\\selectfont,",
                   " color=%s, fill=white, fill opacity=0.92, text opacity=1,",
                   " inner sep=1pt] at (axis cs:0.0007,%s) {%s};"),
            BENCH_COLORS[bench], fmt4(y_lab), bench))
}
pa <- c(pa,
  sprintf("\\draw[gray, dashed, line width=0.8pt] (axis cs:%s,3) -- (axis cs:%s,1200);",
          fmt4(ALPHA_MISS), fmt4(ALPHA_MISS)),
  sprintf(paste0("\\node[anchor=south west, font=\\fontsize{8.5}{9.5}\\selectfont,",
                 " color=black!60] at (axis cs:%s,700) {$\\alpha_{\\mathrm{miss}}$};"),
          fmt4(ALPHA_MISS * 1.05)))
writeLines(pa, file.path(TEX_DIR, "calplanning-panel-a.tex"), useBytes=TRUE)

# Panel b: attainment sweep G1/G2, alpha 0.01-0.20
pb <- c("% generated by process_calplanning.R -- panel b")
for (ax in c("g1_escaped_defect","g2_false_reject")) {
  sub <- att_df[att_df$axis==ax & att_df$alpha>=0.01 & att_df$alpha<=0.20, ]
  sub <- sub[order(sub$alpha, decreasing=TRUE), ]
  coords <- paste(sprintf("(%s,%s)", fmt4(sub$alpha), fmt4(sub$certifiable_fraction)), collapse=" ")
  if (ax=="g1_escaped_defect") {
    pb <- c(pb,
      paste0("\\addplot[blue, mark=o, line width=1.2pt, mark size=2.8pt] coordinates {", coords, "};"),
      "\\addlegendentry{G1 (escaped)}")
  } else {
    pb <- c(pb,
      paste0("\\addplot[red!70!black, mark=square, dashed, line width=1.2pt, mark size=2.8pt] coordinates {", coords, "};"),
      "\\addlegendentry{G2 (false-reject)}")
  }
}
writeLines(pb, file.path(TEX_DIR, "calplanning-panel-b.tex"), useBytes=TRUE)

# Panel c: pool-growth SHORTFALL (1 - certifiable). Truncate each series after
# the first zero so a long y=0 floor does not dominate the shortfall story.
pc <- c("% generated by process_calplanning.R -- panel c (non-certifiable)")
for (bench in BENCHES) {
  for (ax in c("g1_escaped_defect","g2_false_reject")) {
    sub  <- pool_df[pool_df$benchmark==bench & pool_df$axis==ax, ]
    sub  <- sub[order(sub$multiplier), ]
    if (nrow(sub)==0) next
    shortfall <- 1 - sub$certifiable_fraction
    keep <- rep(TRUE, length(shortfall))
    z <- which(shortfall <= 1e-12)
    if (length(z)) keep[seq_along(keep) > z[1]] <- FALSE
    sub <- sub[keep, , drop=FALSE]
    shortfall <- shortfall[keep]
    if (!length(shortfall)) next
    coords   <- paste(sprintf("(%d,%s)", sub$multiplier, fmt4(shortfall)), collapse=" ")
    lbl_b    <- switch(bench, "MVTec AD"="MVTec", "VisA"="VisA", "MPDD"="MPDD")
    lbl_ax   <- if (ax=="g1_escaped_defect") "G1" else "G2"
    dashed   <- if (ax=="g2_false_reject") ", dashed" else ""
    mark     <- if (ax=="g2_false_reject") "square" else "o"
    pc <- c(pc,
      sprintf("\\addplot[%s, mark=%s, line width=1.1pt, mark size=2.5pt%s] coordinates {%s};",
              BENCH_COLORS[bench], mark, dashed, coords),
      sprintf("\\addlegendentry{%s %s}", lbl_b, lbl_ax))
  }
}
writeLines(pc, file.path(TEX_DIR, "calplanning-panel-c.tex"), useBytes=TRUE)

# Panel d: bar chart — G1=defect median, G2=good median + required n_cal marks
BENCH_X <- c("MVTec AD"=0, "VisA"=2, "MPDD"=4)
pd <- c("% generated by process_calplanning.R -- panel d")
g1b <- character(0); g2b <- character(0)
for (bench in BENCHES) {
  o  <- obs_df[obs_df$benchmark==bench, ]
  xb <- BENCH_X[bench]
  g1b <- c(g1b, sprintf("(%s,%s)", fmt4(xb-0.3), fmt4(o$n_cal_defect_median)))
  g2b <- c(g2b, sprintf("(%s,%s)", fmt4(xb+0.3), fmt4(o$n_cal_good_median)))
}
pd <- c(pd,
  paste0("\\addplot[blue, fill=blue] coordinates {", paste(g1b, collapse=" "), "};"),
  "\\addlegendentry{G1 (defect pool)}",
  paste0("\\addplot[red!70!black, fill=red!70!black] coordinates {", paste(g2b, collapse=" "), "};"),
  "\\addlegendentry{G2 (good pool)}")
# Dashed/dotted segments = required n_cal per axis (planning rule)
for (bench in BENCHES) {
  xb <- BENCH_X[bench]
  g1_req <- plan_df$min_pool_required[plan_df$axis=="g1_escaped_defect" & plan_df$benchmark==bench]
  g2_req <- plan_df$min_pool_required[plan_df$axis=="g2_false_reject" & plan_df$benchmark==bench]
  pd <- c(pd,
    sprintf("\\draw[black, dashed, line width=1.1pt] (axis cs:%s,%s) -- (axis cs:%s,%s);",
            fmt4(xb-0.55), fmt4(g1_req), fmt4(xb-0.05), fmt4(g1_req)),
    sprintf("\\draw[black, densely dotted, line width=1.1pt] (axis cs:%s,%s) -- (axis cs:%s,%s);",
            fmt4(xb+0.05), fmt4(g2_req), fmt4(xb+0.55), fmt4(g2_req)))
}
writeLines(pd, file.path(TEX_DIR, "calplanning-panel-d.tex"), useBytes=TRUE)

cat("wrote calplanning TikZ fragments\n")
