#!/usr/bin/env Rscript
# Process deferral.csv for fig-deferral dumbbell panels.
# Reads:  deferral.csv
# Writes: out/deferral-{mvtec,visa,mpdd}.tex

options(warn = 1)

csv_path <- "deferral.csv"
if (!file.exists(csv_path)) {
  stop("FATAL: deferral.csv not found; run R/deferral.R first")
}

df <- read.csv(csv_path, stringsAsFactors = FALSE)

SPECS <- list(
  list(label = "MVTec-AD", key = "mvtec"),
  list(label = "VisA",     key = "visa"),
  list(label = "MPDD",     key = "mpdd")
)

TEX_DIR <- normalizePath(file.path(getwd(), "../out"), mustWork = FALSE)
dir.create(TEX_DIR, recursive = TRUE, showWarnings = FALSE)

fmt4 <- function(x) format(round(x, 4), nsmall = 4, scientific = FALSE, trim = TRUE)

for (spec in SPECS) {
  bdf <- df[df$bench == spec$label, ]
  if (!nrow(bdf)) stop(sprintf("FATAL: no rows for %s", spec$label))

  n <- nrow(bdf)
  # Top-to-bottom category order follows deferral.csv within each benchmark.
  bdf$y <- seq.int(n, 1L)

  lines <- c("% generated by process_deferral.R")
  # Seed 0-4 min-max bands: one thin horizontal rule per backbone per category,
  # drawn behind the seed-0 dots. PatchCore band sits slightly above the row
  # centre, Dinomaly slightly below, so the two backbones' spreads don't merge.
  for (i in seq_len(nrow(bdf))) {
    if (!is.na(bdf$patchcore_lo[i]) && bdf$patchcore_hi[i] > bdf$patchcore_lo[i]) {
      lines <- c(lines, sprintf(
        "\\draw[cPatchcore!55, line width=1.6pt] (axis cs:%s,%s) -- (axis cs:%s,%s);",
        fmt4(bdf$patchcore_lo[i]), fmt4(bdf$y[i] + 0.16),
        fmt4(bdf$patchcore_hi[i]), fmt4(bdf$y[i] + 0.16)))
    }
    if (!is.na(bdf$dinomaly_lo[i]) && bdf$dinomaly_hi[i] > bdf$dinomaly_lo[i]) {
      lines <- c(lines, sprintf(
        "\\draw[cDinomaly!55, line width=1.6pt] (axis cs:%s,%s) -- (axis cs:%s,%s);",
        fmt4(bdf$dinomaly_lo[i]), fmt4(bdf$y[i] - 0.16),
        fmt4(bdf$dinomaly_hi[i]), fmt4(bdf$y[i] - 0.16)))
    }
  }

  pc_coords <- paste(sprintf("(%s,%d)", fmt4(bdf$patchcore), bdf$y), collapse = " ")
  dm_coords <- paste(sprintf("(%s,%d)", fmt4(bdf$dinomaly), bdf$y), collapse = " ")
  lines <- c(
    lines,
    "\\addplot[cPatchcore, only marks, mark=o, line width=0.9pt, mark size=2.3pt] coordinates {",
    paste0("  ", pc_coords),
    "};",
    "\\addplot[cDinomaly, only marks, mark=square, line width=0.9pt, mark size=2.3pt] coordinates {",
    paste0("  ", dm_coords),
    "};"
  )

  writeLines(lines, file.path(TEX_DIR, sprintf("deferral-%s.tex", spec$key)), useBytes = TRUE)
  cat(sprintf("wrote deferral fragment for %s (%d categories)\n", spec$label, n))
}
