#!/usr/bin/env Rscript
# Process opcost analysis data for fig-opcost (4 panels)
# Reads: opcost_analysis_2026-07-16/results.json
#        economic_v1_2026-07-21/results.json
#        latency_2026-07-13/{gate,dinomaly}_latency.json
# Writes: R/opcost_*.csv + out/opcost-panel-[a-d].tex

library(jsonlite)

script_arg <- grep("^--file=", commandArgs(), value = TRUE)
script_path <- if (length(script_arg)) sub("^--file=", "", script_arg[[1]]) else "process_opcost.R"
script_dir <- normalizePath(dirname(script_path), mustWork = TRUE)
setwd(script_dir)

resolve <- function(...) {
  normalizePath(file.path(script_dir, "../../..", ...), mustWork = TRUE)
}

d <- fromJSON(resolve("opcost_analysis_2026-07-16", "results.json"))
# Keep nested lists so null method arms (MPDD b1_no_defer) stay NULL.
econ <- fromJSON(resolve("economic_v1_2026-07-21", "results.json"), simplifyVector = FALSE)
glat <- fromJSON(resolve("latency_2026-07-13", "gate_latency.json"))
dlat <- fromJSON(resolve("latency_2026-07-13", "dinomaly_latency.json"))

BENCHES <- c("MPDD", "VisA", "MVTec-AD")
SCEN <- c("low_volume_precision", "mid_volume_general", "high_volume_commodity")

# ── CSV: panel a grid ──
grid_rows <- list()
for (b in BENCHES) {
  for (s in SCEN) {
    grid_rows[[length(grid_rows) + 1]] <- data.frame(
      benchmark = b, scenario = s,
      gate_cost = d$benchmark_scenario_grid[[b]][[s]]$gate$total_cost_usd_per_hour,
      crc_cost = d$benchmark_scenario_grid[[b]][[s]]$crc$total_cost_usd_per_hour,
      stringsAsFactors = FALSE
    )
  }
}
grid_df <- do.call(rbind, grid_rows)
write.csv(grid_df, "opcost_grid.csv", row.names = FALSE)

# ── CSV: panel b headroom ──
headroom_rows <- list()
for (b in BENCHES) {
  for (s in SCEN) {
    headroom_rows[[length(headroom_rows) + 1]] <- data.frame(
      benchmark = b, scenario = s,
      headroom_multiple = d$breakeven_false_reject_cost_usd[[b]][[s]]$review_cost_headroom_multiple,
      stringsAsFactors = FALSE
    )
  }
}
headroom_df <- do.call(rbind, headroom_rows)
write.csv(headroom_df, "opcost_headroom.csv", row.names = FALSE)

# ── CSV: panel c four-method mid-vol ──
ECON_BENCH <- c("MVTec", "MPDD", "VisA")
ECON_LABEL <- c(MVTec = "MVTec AD", MPDD = "MPDD", VisA = "VisA")
METHODS <- c("gate", "crc", "b1_no_defer", "all_human")
econ_rows <- list()
for (b in ECON_BENCH) {
  cell <- econ$benchmark_scenario_grid[[b]]$mid_volume_general
  for (m in METHODS) {
    v <- cell[[m]]
    cost <- if (is.null(v) || is.null(v$total_cost_usd_per_hour)) {
      NA_real_
    } else {
      as.numeric(v$total_cost_usd_per_hour)
    }
    econ_rows[[length(econ_rows) + 1]] <- data.frame(
      benchmark = unname(ECON_LABEL[[b]]), method = m, cost = cost,
      stringsAsFactors = FALSE
    )
  }
}
econ_df <- do.call(rbind, econ_rows)
write.csv(econ_df, "opcost_fourmethod.csv", row.names = FALSE)

# ── CSV: panel d latency ──
lat_df <- data.frame(
  key = c("backbone_b1", "backbone_b32", "gate_routing"),
  ms = c(
    dlat$batch1_per_image_latency_ms$median,
    dlat$batched_throughput$amortized_ms_per_image,
    glat$route_gate$per_image_amortized_us / 1000
  ),
  cal_ms = glat$calibrate_gate$median_ms,
  stringsAsFactors = FALSE
)
write.csv(lat_df, "opcost_latency.csv", row.names = FALSE)

cat("Wrote opcost CSV files\n")

# ── TikZ fragments ──
TEX_DIR <- normalizePath(file.path(getwd(), "../out"), mustWork = FALSE)
dir.create(TEX_DIR, recursive = TRUE, showWarnings = FALSE)
fmt2 <- function(x) format(round(x, 2), nsmall = 2, scientific = FALSE, trim = TRUE)
fmt3 <- function(x) format(round(x, 3), nsmall = 3, scientific = FALSE, trim = TRUE)

# Panel a
gate_coords <- character(0)
base_coords <- character(0)
for (bi in seq_along(BENCHES)) {
  for (si in seq_along(SCEN)) {
    x <- (bi - 1L) * 3L + (si - 1L)
    row <- grid_df[grid_df$benchmark == BENCHES[bi] & grid_df$scenario == SCEN[si], ]
    gate_coords <- c(gate_coords, sprintf("(%d,%s)", x, fmt2(row$gate_cost)))
    base_coords <- c(base_coords, sprintf("(%d,%s)", x, fmt2(row$crc_cost)))
  }
}
writeLines(c(
  "% generated by process_opcost.R -- panel a",
  sprintf("\\addplot[cGate, fill=cGate] coordinates {%s};", paste(gate_coords, collapse = " ")),
  "\\addlegendentry{gate}",
  sprintf("\\addplot[cBase, fill=cBase] coordinates {%s};", paste(base_coords, collapse = " ")),
  "\\addlegendentry{CRC}"
), file.path(TEX_DIR, "opcost-panel-a.tex"), useBytes = TRUE)

# Panel b -- benchmark lines use the canonical benchmark palette (inspect_style.tex)
HBENCH <- list(
  list(key = "MPDD", color = "cMPDD", mark = "o", label = "MPDD"),
  list(key = "VisA", color = "cVisA", mark = "square", label = "VisA"),
  list(key = "MVTec-AD", color = "cMVTecAD", mark = "triangle", label = "MVTec-AD")
)
panel_b <- c("% generated by process_opcost.R -- panel b")
for (hb in HBENCH) {
  coords <- character(0)
  for (si in seq_along(SCEN)) {
    row <- headroom_df[headroom_df$benchmark == hb$key & headroom_df$scenario == SCEN[si], ]
    coords <- c(coords, sprintf("(%d,%s)", si - 1L, fmt2(row$headroom_multiple)))
  }
  panel_b <- c(panel_b,
    sprintf("\\addplot[%s, mark=%s, line width=1.2pt] coordinates {%s};",
            hb$color, hb$mark, paste(coords, collapse = " ")),
    sprintf("\\addlegendentry{%s}", hb$label))
}
# Annotate every point (compact). Offset labels horizontally by series so the
# three benchmarks' multiplier labels never stack on the curves/each other:
# VisA (top) label above-right, MVTec-AD (mid) below-right, MPDD (bottom)
# below-left. Anchored so the TEXT EXTENT clears the marker. 2026-08-07 fix.
for (hb in HBENCH) {
  for (si in seq_along(SCEN)) {
    row <- headroom_df[headroom_df$benchmark == hb$key & headroom_df$scenario == SCEN[si], ]
    val <- round(row$headroom_multiple)
    if (hb$key == "VisA") { xoff <- 0.10; yfac <- 1.55; anch <- "west" }
    else if (hb$key == "MVTec-AD") { xoff <- 0.12; yfac <- 1.42; anch <- "west" }
    else { xoff <- -0.12; yfac <- 0.60; anch <- "east" }
    # MPDD first point sits on the y-axis; put its label to the RIGHT (below the
    # marker) so it does not collide with the "10^2" y-tick. 2026-08-07 fix.
    if (hb$key == "MPDD" && si == 1L) { xoff <- 0.10; anch <- "west"; yfac <- 0.55 }
    # keep end-of-line labels inside the axis: flip the last point inward and
    # separate the MVTec/MPDD labels vertically so they don't collide at the tail
    if (si == length(SCEN)) {
      if (hb$key == "VisA") { xoff <- -0.10; anch <- "east"; yfac <- 1.5 }
      else if (hb$key == "MVTec-AD") { xoff <- -0.10; anch <- "east"; yfac <- 1.7 }
      else { xoff <- -0.10; anch <- "east"; yfac <- 0.55 }
    }
    panel_b <- c(panel_b, sprintf(
      "\\node[font=\\fontsize{7}{8}\\selectfont, anchor=%s] at (axis cs:%s,%s) {%dx};",
      anch, fmt2((si - 1L) + xoff), fmt2(row$headroom_multiple * yfac), val
    ))
  }
}
panel_b <- c(panel_b,
  "\\draw[black, dashed, line width=1pt] (axis cs:-0.2,1) -- (axis cs:2.2,1);")
# (No in-figure "break-even" text: the caption states "break-even at 1x" and the
# dashed y=1 line is self-evident on the log axis; an in-panel label collided
# with the x-tick labels. 2026-08-07 fix.)
writeLines(panel_b, file.path(TEX_DIR, "opcost-panel-b.tex"), useBytes = TRUE)

# Panel c: 4 methods × 3 benches at mid-vol (x = 0,1,2)
MCOL <- c(gate = "cGate", crc = "cBase", b1_no_defer = "cDefer", all_human = "cAccept")
MLAB <- c(gate = "Gate", crc = "CRC", b1_no_defer = "B1 (no defer)", all_human = "All-human")
panel_c <- c("% generated by process_opcost.R -- panel c")
for (mi in seq_along(METHODS)) {
  m <- METHODS[mi]
  coords <- character(0)
  for (bi in seq_along(ECON_BENCH)) {
    lab <- ECON_LABEL[[ECON_BENCH[bi]]]
    row <- econ_df[econ_df$benchmark == lab & econ_df$method == m, ]
    if (nrow(row) == 0 || is.na(row$cost)) next
    x <- (bi - 1) + (mi - 2.5) * 0.20
    coords <- c(coords, sprintf("(%s,%s)", fmt3(x), fmt2(row$cost)))
  }
  panel_c <- c(panel_c,
    sprintf("\\addplot[%s, fill=%s] coordinates {%s};", MCOL[[m]], MCOL[[m]], paste(coords, collapse = " ")),
    sprintf("\\addlegendentry{%s}", MLAB[[m]]))
}
writeLines(panel_c, file.path(TEX_DIR, "opcost-panel-c.tex"), useBytes = TRUE)

# Panel d: latency bars on a μs log axis (see tikz/fig-opcost.tex panel d).
# Emitting ms with ymin≪1 made pgfplots ybar grow from log-origin y=1, which
# truncated backbone bars and floated the gate bar. All values in μs are >1 so
# default log origin draws bars from the axis floor. Backbone coords share one
# \addplot (consistent bar width); bar shift=0 keeps each bar on its xtick.
gate_us <- glat$route_gate$per_image_amortized_us
cal_ms <- glat$calibrate_gate$median_ms
bb1_us <- lat_df$ms[1] * 1000
bb32_us <- lat_df$ms[2] * 1000
panel_d <- c(
  "% generated by process_opcost.R -- panel d",
  sprintf(
    "\\addplot[cBase, fill=cBase, bar shift=0pt] coordinates {(0,%s) (1,%s)};",
    fmt3(bb1_us), fmt3(bb32_us)
  ),
  sprintf(
    "\\addplot[cGate, fill=cGate, bar shift=0pt] coordinates {(2,%s)};",
    fmt3(gate_us)
  ),
  sprintf(
    "\\node[font=\\fontsize{7}{8}\\selectfont, anchor=south] at (axis cs:0,%s) {$%.2f$ms};",
    fmt3(bb1_us * 1.35), lat_df$ms[1]
  ),
  sprintf(
    "\\node[font=\\fontsize{7}{8}\\selectfont, anchor=south] at (axis cs:1,%s) {$%.2f$ms};",
    fmt3(bb32_us * 1.35), lat_df$ms[2]
  ),
  sprintf(
    "\\node[font=\\fontsize{7}{8}\\selectfont, anchor=south] at (axis cs:2,%s) {$%.1f\\mu$s};",
    fmt3(max(gate_us * 3.2, 8)), gate_us
  ),
  sprintf(
    paste0(
      "\\node[anchor=east, font=\\fontsize{7}{8}\\selectfont, text=black!70, ",
      "align=right] at (rel axis cs:0.97,0.52) {cal: $%.1f$ms\\\\(one-time)};"
    ),
    cal_ms
  )
)
writeLines(panel_d, file.path(TEX_DIR, "opcost-panel-d.tex"), useBytes = TRUE)

cat(sprintf("opcost cost range: %.1f -- %.1f\n", min(grid_df$gate_cost, grid_df$crc_cost),
            max(grid_df$gate_cost, grid_df$crc_cost)))
cat("wrote opcost fragments a–d\n")
