#!/usr/bin/env Rscript
# Process baseline comparison data for fig-crcbaseline (3-panel expanded)
# Reads: baseline_comparison_2026-07-15/results.json
# Writes: R/crcbaseline_*.csv (panel_a, panel_b, panel_c)

library(jsonlite)

script_arg <- grep("^--file=", commandArgs(), value = TRUE)
script_path <- if (length(script_arg)) sub("^--file=", "", script_arg[[1]]) else "process_crcbaseline.R"
script_dir <- normalizePath(dirname(script_path), mustWork = TRUE)
json_path <- normalizePath(file.path(script_dir, "../../../baseline_comparison_2026-07-15/results.json"), mustWork = TRUE)
setwd(script_dir)

d <- fromJSON(json_path)
BENCH_ORDER <- list(
  list(key="MPDD", label="MPDD"),
  list(key="VisA", label="VisA"),
  list(key="MVTec-AD", label="MVTec AD")
)

# Panel a: dot strip comparison
a_rows <- list()
for (bi in seq_along(BENCH_ORDER)) {
  bench <- BENCH_ORDER[[bi]]
  bk <- bench$key
  blabel <- bench$label
  e <- d$benchmarks[[bk]]

  metrics <- list(
    list(key="mean_false_reject_rate", label="False-reject"),
    list(key="mean_escaped_defect_rate", label="Escaped"),
    list(key="mean_deferral_rate", label="Deferral")
  )

  for (metric in metrics) {
    g_val <- e$our_gate_published[[metric$key]] * 100
    c_val <- e$crc_baseline[[metric$key]] * 100

    a_rows[[length(a_rows)+1]] <- data.frame(
      benchmark = blabel,
      y_idx = bi - 1,
      metric = metric$label,
      gate_val = g_val,
      crc_val = c_val,
      stringsAsFactors = FALSE
    )
  }
}
a_df <- do.call(rbind, a_rows)
write.csv(a_df, "crcbaseline_panel_a.csv", row.names = FALSE)

# Panel b: selective-prediction risk-at-coverage (VisA)
e_visa <- d$benchmarks$VisA
b_rows <- list()
for (bb in c("patchcore", "dinomaly")) {
  sp <- e_visa$selective_baseline$per_backbone[[bb]]
  pts <- sp$risk_at_coverage
  for (i in seq_along(pts$coverage)) {
    b_rows[[length(b_rows)+1]] <- data.frame(
      backbone = bb,
      coverage = pts$coverage[i],
      selective_risk = pts$selective_risk[i] * 100,
      stringsAsFactors = FALSE
    )
  }
}
b_df <- do.call(rbind, b_rows)
# Guarantee threshold alpha_fr = 0.05 (the certified 5% false-reject ceiling),
# NOT the realized FR. Panel b shows that no coverage level meets this guarantee.
b_df$gate_fr_alpha <- 5.0
b_df$gate_fr_realized <- e_visa$our_gate_published$mean_false_reject_rate * 100
write.csv(b_df, "crcbaseline_panel_b.csv", row.names = FALSE)

# Panel c: per-backbone G2 certified split
c_rows <- list()
for (bench in BENCH_ORDER) {
  bk <- bench$key
  blabel <- bench$label

  for (bb in c("patchcore", "dinomaly")) {
    gate_bb <- d$benchmarks[[bk]]$our_gate_published$per_backbone[[bb]]
    crc_bb <- d$benchmarks[[bk]]$crc_baseline$per_backbone[[bb]]

    gate_frac <- gate_bb$g2_certified_cells / gate_bb$n_cells * 100
    crc_frac <- crc_bb$g2_certified_cells / crc_bb$n_cells * 100

    c_rows[[length(c_rows)+1]] <- data.frame(
      benchmark = blabel,
      backbone = bb,
      gate_frac = gate_frac,
      crc_frac = crc_frac,
      stringsAsFactors = FALSE
    )
  }
}
c_df <- do.call(rbind, c_rows)
write.csv(c_df, "crcbaseline_panel_c.csv", row.names = FALSE)

cat("Wrote crcbaseline CSV files\n")

# ── TikZ fragment emitter ────────────────────────────────────
TEX_DIR <- normalizePath(file.path(getwd(), "../out"), mustWork = FALSE)
dir.create(TEX_DIR, recursive = TRUE, showWarnings = FALSE)

fmt4 <- function(x) format(round(x, 4), nsmall=4, scientific=FALSE, trim=TRUE)

# Panel a: dot-strip comparison (gate hollow, CRC filled per metric per benchmark)
# y_idx: MPDD=0, VisA=1, MVTec AD=2
# Hollow = gate, filled = CRC. Legend entries attach to the hollow (gate) marks.
METRICS <- list(
  list(label="False-reject", fr_color="cFalseReject",
       solid="only marks, mark=square*, mark size=2.4pt",
       hollow="only marks, mark=square, draw=cFalseReject, mark size=2.4pt"),
  list(label="Escaped", fr_color="cEscaped",
       solid="only marks, mark=*, mark size=2.2pt",
       hollow="only marks, mark=o, mark size=2.2pt"),
  list(label="Deferral", fr_color="cDeferral",
       solid="only marks, mark=triangle*, mark size=2.6pt",
       hollow="only marks, mark=triangle, draw=cDeferral, mark size=2.6pt")
)

pa_lines <- c("% generated by process_crcbaseline.R")
for (m in METRICS) {
  mdf <- a_df[a_df$metric == m$label, ]
  mdf <- mdf[order(mdf$y_idx), ]
  crc_coords <- paste(sprintf("(%s,%d)", fmt4(mdf$crc_val), mdf$y_idx), collapse=" ")
  gate_coords <- paste(sprintf("(%s,%d)", fmt4(mdf$gate_val), mdf$y_idx), collapse=" ")
  # CRC filled first (forget plot), then gate hollow with legend entry
  pa_lines <- c(pa_lines,
    sprintf("\\addplot[%s, %s, forget plot] coordinates {%s};", m$fr_color, m$solid, crc_coords),
    sprintf("\\addplot[%s, %s] coordinates {%s};", m$fr_color, m$hollow, gate_coords),
    sprintf("\\addlegendentry{%s}", m$label))
}
# MPDD FR annotation (hardcoded geometry but actual values from data)
mpdd_crc_fr <- a_df[a_df$benchmark == "MPDD" & a_df$metric == "False-reject", "crc_val"]
mpdd_gate_fr <- a_df[a_df$benchmark == "MPDD" & a_df$metric == "False-reject", "gate_val"]
pa_lines <- c(pa_lines,
  sprintf("\\draw[cFalseReject, thick, ->] (axis cs:%s,0.32) -- (axis cs:%s,0.05);",
          fmt4(mpdd_crc_fr), fmt4(mpdd_crc_fr)),
  sprintf("\\node[font=\\axislabelfont, text=black, anchor=south] at (axis cs:%s,0.36) {$%.1f\\%%$ vs.\\ $%.1f\\%%$};",
          fmt4(mpdd_crc_fr), mpdd_crc_fr, mpdd_gate_fr))
writeLines(pa_lines, file.path(TEX_DIR, "crcbaseline-panel-a.tex"), useBytes=TRUE)

# Panel b: VisA selective-prediction risk-at-coverage
pb_lines <- c("% generated by process_crcbaseline.R")
alpha_fr <- b_df$gate_fr_alpha[1]
# sort by coverage descending for natural left-to-right plot
for (bb in c("patchcore", "dinomaly")) {
  bbd <- b_df[b_df$backbone == bb, ]
  bbd <- bbd[order(bbd$coverage), ]
  coords <- paste(sprintf("(%s,%s)", fmt4(bbd$coverage), fmt4(bbd$selective_risk)), collapse=" ")
  if (bb == "patchcore") {
    pb_lines <- c(pb_lines,
      sprintf("\\addplot[cPatchcore, mark=o, line width=1.1pt, mark size=2.2pt] coordinates {%s};", coords),
      "\\addlegendentry{PatchCore}")
  } else {
    pb_lines <- c(pb_lines,
      sprintf("\\addplot[cDinomaly, mark=square, line width=1.1pt, mark size=2.2pt] coordinates {%s};", coords),
      "\\addlegendentry{Dinomaly}")
  }
}
pb_lines <- c(pb_lines,
  sprintf("\\draw[gray, dashed, line width=0.9pt] (axis cs:0,%s) -- (axis cs:1.02,%s);",
          fmt4(alpha_fr), fmt4(alpha_fr)),
  # Outside the right spine: in-axis NE sits on Dinomaly (cov≈1 risk>5%) and
  # under-line placement collides with the selective-risk series.
  sprintf(paste0("\\node[anchor=west, font=\\figfont,",
                 " text=black] at (axis cs:1.05,%s)",
                 " {$\\alpha_{\\mathrm{fr}}=%.0f\\%%$};"),
          fmt4(alpha_fr), alpha_fr))
writeLines(pb_lines, file.path(TEX_DIR, "crcbaseline-panel-b.tex"), useBytes=TRUE)

# Panel c: per-backbone G2 certified bars
# x positions: MPDD=0, VisA=1, MVTec AD=2; patchcore offset -0.18, dinomaly +0.18
pc_lines <- c("% generated by process_crcbaseline.R")
BENCH_X <- c("MPDD"=0, "VisA"=1, "MVTec AD"=2)
for (bb_name in c("patchcore", "dinomaly")) {
  bbd <- c_df[c_df$backbone == bb_name, ]
  coords <- character(0)
  off <- if (bb_name == "patchcore") -0.18 else 0.18
  for (bi in seq_len(nrow(bbd))) {
    bench <- bbd$benchmark[bi]
    x     <- BENCH_X[bench] + off
    coords <- c(coords, sprintf("(%s,%s)", fmt4(x), fmt4(bbd$gate_frac[bi])))
  }
  if (bb_name == "patchcore") {
    pc_lines <- c(pc_lines,
      sprintf("\\addplot[cPatchcore, fill=cPatchcore] coordinates {%s};", paste(coords, collapse=" ")),
      "\\addlegendentry{PatchCore}")
  } else {
    pc_lines <- c(pc_lines,
      sprintf("\\addplot[cDinomaly, fill=cDinomaly] coordinates {%s};", paste(coords, collapse=" ")),
      "\\addlegendentry{Dinomaly}")
  }
}
writeLines(pc_lines, file.path(TEX_DIR, "crcbaseline-panel-c.tex"), useBytes=TRUE)

cat("wrote crcbaseline fragments\n")
